onebot:
  ip: 0.0.0.0
  path: /ws
  port: 1145
spring:
  database:
    dataType: SQLITE
    mysqlPassword: ''
    mysqlUrl: ''
    mysqlUser: ''
  jackson:
    dateformat: yyyy-MM-dd HH:mm:ss
    timezone: Asia/Shanghai
telegram:
  bot:
    token: 7497756770:AAGCoySqdF66FTR3qZTvSwWYB7hsp1T2bgE
    username: Hoshiran

